# This file is generated by Terraformm, do not edit it directly.
# To update it just execute "terraform apply" again after changing the "regions" parameter.


module "regional_resources_us-east-1" {
  count = contains(var.regions, "us-east-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_sqs_queue_url = var.autospotting_sqs_queue_url
  autospotting_sqs_queue_arn = var.autospotting_sqs_queue_arn
  event_bus_arn              = data.aws_cloudwatch_event_bus.default.arn
  main_region                = data.aws_region.current.name
  put_event_role_arn         = var.put_event_role_arn

  providers = {
    aws = aws.us-east-1
  }
}
module "regional_resources_us-east-2" {
  count = contains(var.regions, "us-east-2") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_sqs_queue_url = var.autospotting_sqs_queue_url
  autospotting_sqs_queue_arn = var.autospotting_sqs_queue_arn
  event_bus_arn              = data.aws_cloudwatch_event_bus.default.arn
  main_region                = data.aws_region.current.name
  put_event_role_arn         = var.put_event_role_arn

  providers = {
    aws = aws.us-east-2
  }
}
module "regional_resources_us-west-1" {
  count = contains(var.regions, "us-west-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_sqs_queue_url = var.autospotting_sqs_queue_url
  autospotting_sqs_queue_arn = var.autospotting_sqs_queue_arn
  event_bus_arn              = data.aws_cloudwatch_event_bus.default.arn
  main_region                = data.aws_region.current.name
  put_event_role_arn         = var.put_event_role_arn

  providers = {
    aws = aws.us-west-1
  }
}
module "regional_resources_us-west-2" {
  count = contains(var.regions, "us-west-2") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_sqs_queue_url = var.autospotting_sqs_queue_url
  autospotting_sqs_queue_arn = var.autospotting_sqs_queue_arn
  event_bus_arn              = data.aws_cloudwatch_event_bus.default.arn
  main_region                = data.aws_region.current.name
  put_event_role_arn         = var.put_event_role_arn

  providers = {
    aws = aws.us-west-2
  }
}
