# This file is generated by Terraformm, do not edit it directly.
# To update it just execute "terraform apply" again after changing the "regions" parameter.

module "regional_resources_ap-northeast-1" {
 count  = contains(var.regions,"ap-northeast-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-northeast-1
  }
}
module "regional_resources_ap-northeast-2" {
 count  = contains(var.regions,"ap-northeast-2") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-northeast-2
  }
}
module "regional_resources_ap-northeast-3" {
 count  = contains(var.regions,"ap-northeast-3") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-northeast-3
  }
}
module "regional_resources_ap-south-1" {
 count  = contains(var.regions,"ap-south-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-south-1
  }
}
module "regional_resources_ap-southeast-1" {
 count  = contains(var.regions,"ap-southeast-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-southeast-1
  }
}
module "regional_resources_ap-southeast-2" {
 count  = contains(var.regions,"ap-southeast-2") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ap-southeast-2
  }
}
module "regional_resources_ca-central-1" {
 count  = contains(var.regions,"ca-central-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.ca-central-1
  }
}
module "regional_resources_eu-central-1" {
 count  = contains(var.regions,"eu-central-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-central-1
  }
}
module "regional_resources_eu-north-1" {
 count  = contains(var.regions,"eu-north-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-north-1
  }
}
module "regional_resources_eu-west-1" {
 count  = contains(var.regions,"eu-west-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-west-1
  }
}
module "regional_resources_eu-west-2" {
 count  = contains(var.regions,"eu-west-2") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-west-2
  }
}
module "regional_resources_eu-west-3" {
 count  = contains(var.regions,"eu-west-3") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.eu-west-3
  }
}
module "regional_resources_sa-east-1" {
 count  = contains(var.regions,"sa-east-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.sa-east-1
  }
}
module "regional_resources_us-east-1" {
 count  = contains(var.regions,"us-east-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.us-east-1
  }
}
module "regional_resources_us-east-2" {
 count  = contains(var.regions,"us-east-2") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.us-east-2
  }
}
module "regional_resources_us-west-1" {
 count  = contains(var.regions,"us-west-1") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.us-west-1
  }
}
module "regional_resources_us-west-2" {
 count  = contains(var.regions,"us-west-2") ? 1 : 0

  source        = "./resources"
  label_context = var.label_context

  autospotting_lambda_arn = var.autospotting_lambda_arn
  lambda_iam_role         = aws_iam_role.regional_role

  providers = {
    aws = aws.us-west-2
  }
}
